# Generated by Django 5.1.7 on 2025-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0.0, help_text='CPF do usuário.', max_length=11, verbose_name='CPF:'),
        ),
    ]
